
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[283] =
    {   0,
        0,    0,   91,   90,   88,   89,   66,   90,   87,   40,
       41,   81,   72,   73,   38,   36,   78,   37,   79,   39,
       82,   82,   80,   85,   63,   65,   64,   86,   74,   75,
       42,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   76,   86,   77,   67,    0,
       84,    0,    0,   50,   57,   51,   45,   87,    0,    0,
       84,    0,   48,   60,   46,   61,   47,    0,   83,    0,
        1,   49,    0,    0,   82,    0,    0,    0,   82,   70,
       59,   43,   68,   62,   69,   44,   86,   53,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   14,   16,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   52,   58,    0,    0,
       56,   87,    0,    0,   71,    0,    0,    0,    1,    0,
       82,   82,   82,    0,   83,   83,   54,   55,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   12,
       86,   86,   86,   28,   19,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   27,    0,    0,    0,   83,    0,
        2,    0,   83,   82,    0,   83,    0,   86,   30,   86,
        4,    5,   86,   86,   86,   86,   10,   86,   86,   86,
       13,   15,   86,   86,   86,   86,   86,   86,   31,   86,

       86,   86,   86,   26,    0,    0,   83,   83,    0,   83,
       86,    3,    6,   86,   86,    9,   86,   86,   86,   86,
       86,   86,   33,   21,   86,   86,   86,   86,   86,    0,
        0,   83,   35,   86,   86,   86,   86,   86,   17,   86,
       86,   86,   22,   23,   32,   24,   25,    0,    0,   86,
        8,   86,   86,   29,   86,   20,   34,    0,    0,    7,
       86,   86,   86,    0,    0,   86,   86,   18,    0,    0,
       86,   86,    0,    0,   86,   11,    0,    0,   86,    0,
        0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   21,   20,   22,   20,   23,   23,   24,   25,   26,
       27,   28,    7,    7,   29,   29,   29,   29,   30,   29,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,    7,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   46,   53,   54,   55,   56,   57,   58,   59,
       60,   46,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    3,    4,    5,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    6,    6,
        6,    6,    6,    3,    3,    3,    3,    3,    6,    6,
        7,    7,    3,    3,    3,    7,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        3,    6,    3,    3
    } ;

static yyconst flex_int16_t yy_base[289] =
    {   0,
        0,    0,  561,  562,  562,  562,  533,   59,  562,  532,
       57,   63,  562,  562,  531,   56,  562,   55,   55,   67,
       99,  156,  530,  562,   63,  529,   59,    0,  562,  562,
      528,  502,   40,   44,  512,   48,   61,  501,   57,  514,
       60,   74,   69,  490,  512,  562,   74,  562,  562,  122,
      562,  128,  129,  562,  562,  562,  521,  139,  537,  140,
      141,  147,  562,  562,  562,  562,  562,  529,  183,  532,
        0,  562,  240,  189,  158,  134,  221,    0,    0,  562,
      562,  517,  562,  562,  562,  516,    0,  562,  490,  490,
      499,  485,  501,  487,  494,  481,  495,  485,  481,  478,

      480,  474,    0,  476,  472,  469,  468,  456,  448,  442,
      445,  446,  440,  447,  439,  437,  562,    0,  479,  190,
      562,  562,  478,  182,  562,  252,  473,   90,    0,  265,
      153,    0,  270,  289,  298,  277,  562,  562,  444,  435,
      445,  440,  430,   87,  106,  438,  441,  429,  439,    0,
      436,  423,  419,  428,    0,  421,  416,  421,  407,  421,
      412,   81,  390,  398,    0,  216,  227,  303,  310,  158,
      562,  418,  315,    0,  321,  326,  344,  376,    0,  378,
        0,    0,  360,  368,  349,  351,    0,  334,  330,  328,
        0,    0,  309,  308,  318,  272,  275,  262,    0,  274,

      257,  267,  266,    0,  346,  349,  349,  354,  359,  372,
      261,    0,    0,  244,  228,    0,  226,  221,  234,  200,
      210,  207,  201,    0,  198,  192,  196,  183,  192,  347,
      379,  388,    0,  178,  178,  188,  172,  195,    0,  177,
      166,  149,    0,    0,    0,    0,    0,  390,  392,  157,
        0,  158,  140,    0,  146,    0,    0,  393,  407,    0,
      145,  118,  131,  408,  411,  124,  123,    0,  413,  417,
      128,  116,  418,  430,   95,    0,  431,  446,  113,  432,
      455,  562,  497,  502,  505,  512,  519,  108
    } ;

static yyconst flex_int16_t yy_def[289] =
    {   0,
      282,    1,  282,  282,  282,  282,  282,  283,  282,  282,
      282,  284,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  285,  282,  282,
      282,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  282,  285,  282,  282,  283,
      282,  283,  283,  282,  282,  282,  282,  284,  282,  284,
      284,  284,  282,  282,  282,  282,  282,  282,  282,  286,
      287,  282,  282,  282,   21,   75,  282,  288,   22,  282,
      282,  282,  282,  282,  282,  282,  285,  282,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  282,  285,  282,  283,
      282,  282,  282,  284,  282,  282,  286,  282,  287,  282,
       73,  288,  288,  282,  282,  282,  282,  282,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  283,  284,  282,  282,  282,
      282,  282,  282,  133,  282,  282,  282,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  283,  284,  282,  282,  282,  282,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  283,
      284,  282,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  283,  284,  285,
      285,  285,  285,  285,  285,  285,  285,  283,  284,  285,
      285,  285,  285,  283,  284,  285,  285,  285,  283,  284,
      285,  285,  283,  284,  285,  285,  283,  284,  285,  283,
      284,    0,  282,  282,  282,  282,  282,  282
    } ;

static yyconst flex_int16_t yy_nxt[627] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   28,   29,   30,   31,    9,   32,   33,   34,   35,
       36,   37,   38,   28,   39,   28,   28,   28,   40,   28,
       28,   41,   42,   43,   44,   28,   45,   28,   28,   28,
       46,   47,   48,    9,   51,   55,   58,   59,   52,   64,
       66,   68,   61,   69,   69,   69,   69,   69,   81,   70,
       92,   67,   65,   56,   71,   85,   86,   93,   82,   83,
       90,   57,   91,   72,   94,   96,  107,   98,  103,   53,

      117,   97,  170,   62,   73,  104,  105,  171,   99,  112,
      109,  100,  108,  132,  110,   74,  101,   75,   75,   75,
       75,   76,  122,  113,  172,  201,  114,   51,   77,  111,
       78,   52,  119,   51,   51,  118,  202,   52,   52,   77,
      183,  184,  185,  282,  282,  123,  186,  279,   61,   61,
       61,  282,   76,   76,   76,   76,   61,   78,  282,  276,
       73,   77,   53,   77,  275,  272,  282,  271,   53,   53,
      170,  268,   74,  267,   79,   79,   79,   79,   79,   62,
       62,   62,  120,  266,  263,   77,  282,   62,  126,  282,
      262,   61,  172,  261,  134,   51,   77,  260,  257,   52,

      124,   69,   69,   69,   69,   69,  256,  135,  135,  135,
      135,  135,  126,  255,  132,  254,  282,   77,  134,   77,
      167,   51,   62,  126,  253,   52,  130,  252,  166,  134,
       53,  282,  251,  250,  130,  247,   61,  246,  245,  136,
      136,  136,  136,  136,  126,  130,  244,  243,  242,  241,
      134,  240,  205,  130,  239,  238,   53,  168,  131,  131,
      131,  131,  131,  206,  237,  168,  236,   62,  132,  132,
      169,  169,  169,  169,  169,  235,  132,  132,  132,  132,
      132,  132,  130,  173,  173,  173,  173,  173,  174,  174,
      174,  174,  174,  234,  175,  136,  136,  136,  136,  136,

      233,  133,  175,  177,  229,  228,  227,  176,  176,  176,
      176,  176,  226,  168,  225,  224,  135,  135,  135,  135,
      135,  207,  207,  207,  207,  207,  223,  177,  169,  169,
      169,  169,  169,  173,  173,  173,  173,  173,  177,  208,
      208,  208,  208,  208,  176,  176,  176,  176,  176,  209,
      175,   51,   51,  282,  222,   52,   52,  209,   61,  177,
      221,  220,  210,  210,  210,  210,  210,  207,  207,  207,
      207,  207,  208,  208,  208,  208,  208,  232,  232,  232,
      232,  232,  219,  282,  218,  217,   53,  248,   61,   62,
      210,  210,  210,  210,  210,   51,  282,  230,   51,   52,

      231,   61,   52,  216,  215,  209,  232,  232,  232,  232,
      232,  282,  214,   51,  213,  282,   61,   52,   51,  249,
       61,  282,   52,   51,  212,  211,   61,   52,  264,  258,
       53,  259,   62,   53,  282,  127,   51,   51,  204,   61,
       52,   52,  265,  120,  203,  124,  269,   62,   53,  270,
      282,   62,  200,   53,  277,   61,  273,   62,   53,  282,
      274,  199,  198,  197,   61,  196,  278,  195,  194,  193,
       62,   53,   53,  192,  191,  190,  189,  188,  187,  182,
      181,  180,  179,  280,  178,  128,   62,   60,   50,  165,
      164,  163,  162,  161,  160,   62,  159,  158,  281,   50,

      157,   50,   50,   50,   60,   60,  156,   60,   60,   87,
       87,   87,  127,  127,  127,  127,  127,  127,  127,  129,
      155,  129,  129,  129,  129,  129,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  128,  125,  122,  121,  116,  115,
      106,  102,   95,   89,   88,   84,   80,   63,   54,   49,
      282,    3,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282
    } ;

static yyconst flex_int16_t yy_chk[627] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   11,   12,   12,    8,   16,
       18,   19,   12,   19,   19,   19,   19,   19,   25,   20,
       34,   18,   16,   11,   20,   27,   27,   34,   25,   25,
       33,   11,   33,   20,   34,   36,   41,   37,   39,    8,

       47,   36,  128,   12,   21,   39,   39,  128,   37,   43,
       42,   37,   41,  288,   42,   21,   37,   21,   21,   21,
       21,   21,  279,   43,  128,  162,   43,   50,   21,   42,
       21,   50,   52,   52,   53,   47,  162,   52,   53,   21,
      144,  144,  145,   58,   60,   61,  145,  275,   58,   60,
       61,   62,   76,   76,   76,   76,   62,   21,  131,  272,
       21,   22,   50,   75,  271,  267,  131,  266,   52,   53,
      170,  263,   22,  262,   22,   22,   22,   22,   22,   58,
       60,   61,   53,  261,  255,   22,  124,   62,   69,   75,
      253,  124,  170,  252,   74,  120,   22,  250,  242,  120,

       62,   69,   69,   69,   69,   69,  241,   74,   74,   74,
       74,   74,   69,  240,  131,  238,   75,   22,   74,   75,
      124,  166,  124,   69,  237,  166,   77,  236,  120,   74,
      120,  167,  235,  234,   77,  229,  167,  228,  227,   77,
       77,   77,   77,   77,   69,   73,  226,  225,  223,  222,
       74,  221,  166,   73,  220,  219,  166,  126,   73,   73,
       73,   73,   73,  167,  218,  126,  217,  167,   73,   73,
      126,  126,  126,  126,  126,  215,   73,   73,   73,   73,
       73,   73,   77,  130,  130,  130,  130,  130,  133,  133,
      133,  133,  133,  214,  134,  136,  136,  136,  136,  136,

      211,   73,  134,  135,  203,  202,  201,  134,  134,  134,
      134,  134,  200,  126,  198,  197,  135,  135,  135,  135,
      135,  168,  168,  168,  168,  168,  196,  135,  169,  169,
      169,  169,  169,  173,  173,  173,  173,  173,  135,  175,
      175,  175,  175,  175,  176,  176,  176,  176,  176,  177,
      134,  205,  230,  206,  195,  205,  230,  177,  206,  135,
      194,  193,  177,  177,  177,  177,  177,  207,  207,  207,
      207,  207,  208,  208,  208,  208,  208,  209,  209,  209,
      209,  209,  190,  231,  189,  188,  205,  230,  231,  206,
      210,  210,  210,  210,  210,  248,  249,  205,  258,  248,

      206,  249,  258,  186,  185,  177,  232,  232,  232,  232,
      232,  259,  184,  264,  183,  265,  259,  264,  269,  231,
      265,  270,  269,  273,  180,  178,  270,  273,  258,  248,
      248,  249,  249,  258,  274,  172,  277,  280,  164,  274,
      277,  280,  259,  248,  163,  249,  264,  259,  264,  265,
      278,  265,  161,  269,  273,  278,  269,  270,  273,  281,
      270,  160,  159,  158,  281,  157,  274,  156,  154,  153,
      274,  277,  280,  152,  151,  149,  148,  147,  146,  143,
      142,  141,  140,  277,  139,  127,  278,  123,  119,  116,
      115,  114,  113,  112,  111,  281,  110,  109,  278,  283,

      108,  283,  283,  283,  284,  284,  107,  284,  284,  285,
      285,  285,  286,  286,  286,  286,  286,  286,  286,  287,
      106,  287,  287,  287,  287,  287,  105,  104,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   86,   82,   70,   68,   59,   57,   45,   44,
       40,   38,   35,   32,   31,   26,   23,   15,   10,    7,
        3,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "go.l"
#line 2 "go.l"
#include <stdio.h>
#include <stdlib.h>
#include "y.tab.h"

int line_num = 1;
int char_num = 1;

char* tokens[3000];
size_t numToken = 0;
#line 700 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 116 "go.l"

#line 889 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 283 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 562 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "go.l"
{
				printf("Eating ...%s\n", yytext);
				char_num += strlen(yytext);
			}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 122 "go.l"
{
			printf("Eating ...%s\n", yytext);
			for(int i = 0; i < strlen(yytext); i++)
				if(yytext[i] == '\n')
					line_num++;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 128 "go.l"
{printf("%s\n", yytext); return break_;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "go.l"
{printf("%s\n", yytext); return case_;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "go.l"
{printf("%s\n", yytext); return chan_;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 131 "go.l"
{printf("%s\n", yytext); return const_;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 132 "go.l"
{printf("%s\n", yytext); return continue_;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 133 "go.l"
{printf("%s\n", yytext); return default_;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 134 "go.l"
{printf("%s\n", yytext); return defer_;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 135 "go.l"
{printf("%s\n", yytext); return else_;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "go.l"
{printf("%s\n", yytext); return fallthrough_;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 137 "go.l"
{printf("%s\n", yytext); return for_;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "go.l"
{printf("%s\n", yytext); return func_;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "go.l"
{printf("%s\n", yytext); return go_;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 140 "go.l"
{printf("%s\n", yytext); return goto_;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "go.l"
{printf("%s\n", yytext); return if_;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 142 "go.l"
{printf("%s\n", yytext); return import_;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 143 "go.l"
{printf("%s\n", yytext); return interface_;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 144 "go.l"
{printf("%s\n", yytext); return map_;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 145 "go.l"
{printf("%s\n", yytext); return package_;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "go.l"
{printf("%s\n", yytext); return range_;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 147 "go.l"
{printf("%s\n", yytext); return return_;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 148 "go.l"
{printf("%s\n", yytext); return select_;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 149 "go.l"
{printf("%s\n", yytext); return struct_;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 150 "go.l"
{printf("%s\n", yytext); return switch_;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 151 "go.l"
{printf("%s\n", yytext); return type_;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 152 "go.l"
{printf("%s\n", yytext); return var_;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 153 "go.l"
{printf("%s\n", yytext); return int_;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 154 "go.l"
{printf("%s\n", yytext); return float_;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 155 "go.l"
{printf("%s\n", yytext); return bool_;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 156 "go.l"
{printf("%s\n", yytext); return rune_;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 157 "go.l"
{printf("%s\n", yytext); return string_;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 158 "go.l"
{printf("%s\n", yytext); return print_;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 159 "go.l"
{printf("%s\n", yytext); return println_;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 160 "go.l"
{printf("%s\n", yytext); return append_;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 161 "go.l"
{printf("%s\n", yytext); return add_;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 162 "go.l"
{printf("%s\n", yytext); return minus_;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 163 "go.l"
{printf("%s\n", yytext); return mult_;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 164 "go.l"
{printf("%s\n", yytext); return div_;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 165 "go.l"
{printf("%s\n", yytext); return mod_;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 166 "go.l"
{printf("%s\n", yytext); return amp_;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 167 "go.l"
{printf("%s\n", yytext); return caret_;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 168 "go.l"
{printf("%s\n", yytext); return ls_;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 169 "go.l"
{printf("%s\n", yytext); return rs_;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 170 "go.l"
{printf("%s\n", yytext); return unknown_;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 171 "go.l"
{printf("%s\n", yytext); return add_eq_;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 172 "go.l"
{printf("%s\n", yytext); return minus_eq_;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 173 "go.l"
{printf("%s\n", yytext); return mult_eq_;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 174 "go.l"
{printf("%s\n", yytext); return div_eq_;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 175 "go.l"
{printf("%s\n", yytext); return mod_eq_;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 176 "go.l"
{printf("%s\n", yytext); return amp_eq_;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 177 "go.l"
{printf("%s\n", yytext); return vb_eq_;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 178 "go.l"
{printf("%s\n", yytext); return caret_eq_;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 179 "go.l"
{printf("%s\n", yytext); return ls_eq_;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 180 "go.l"
{printf("%s\n", yytext); return rs_eq_;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 181 "go.l"
{printf("%s\n", yytext); return unknown_eq_;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 182 "go.l"
{printf("%s\n", yytext); return and_;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 183 "go.l"
{printf("%s\n", yytext); return or_;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 184 "go.l"
{printf("%s\n", yytext); return arrow_;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 185 "go.l"
{printf("%s\n", yytext); return incre_;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 186 "go.l"
{printf("%s\n", yytext); return decre_;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 187 "go.l"
{printf("%s\n", yytext); return equality_;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 188 "go.l"
{printf("%s\n", yytext); return lt_;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 189 "go.l"
{printf("%s\n", yytext); return gt_;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 190 "go.l"
{printf("%s\n", yytext); return eq_;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 191 "go.l"
{printf("%s\n", yytext); return not_;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 192 "go.l"
{printf("%s\n", yytext); return not_eq_;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 193 "go.l"
{printf("%s\n", yytext); return lteq_;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 194 "go.l"
{printf("%s\n", yytext); return gteq_;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 195 "go.l"
{printf("%s\n", yytext); return decla_;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 196 "go.l"
{printf("%s\n", yytext); return etc_;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 197 "go.l"
{printf("%s\n", yytext); return lrbrac_;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 198 "go.l"
{printf("%s\n", yytext); return rrbrac_;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 199 "go.l"
{printf("%s\n", yytext); return lsbrac_;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 200 "go.l"
{printf("%s\n", yytext); return rsbrac_;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 201 "go.l"
{printf("%s\n", yytext); return lcbrac_;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 202 "go.l"
{printf("%s\n", yytext); return rcbrac_;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 203 "go.l"
{printf("%s\n", yytext); return comma_;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 204 "go.l"
{printf("%s\n", yytext); return dot_;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 205 "go.l"
{printf("%s\n", yytext); return colon_;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 206 "go.l"
{printf("%s\n", yytext); return vb_;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 208 "go.l"
{
					char ** temp;
					printf("%s\n", yytext);
					yylval.int_val = strtol(yytext, temp, 10);
					if(temp != NULL){
						printf("Integer parse error %s\n", yytext);
						return error_;
					}
					return int_lit_;
				}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 219 "go.l"
{
					char ** temp;
					printf("%s\n", yytext);
					yylval.float_val = strtof(yytext, temp);
					if(temp != NULL){
						printf("Integer parse error %s\n", yytext);
						return error_;
					}
					return float_lit_;
				}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 230 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return string_lit_;
				}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 242 "go.l"
{printf("%s\n", yytext); return semi_colon_;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 244 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return id_;
				}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 256 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return rune_lit_;
				}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 268 "go.l"
char_num++;
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 269 "go.l"
{
					line_num += 1;
					printf("NEW LINE\n");
					//return new_line_;
				}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 274 "go.l"
ECHO;
	YY_BREAK
#line 1484 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 283 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 283 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 282);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 274 "go.l"



