
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[277] =
    {   0,
       87,   87,   90,   89,   86,   88,   64,   89,   85,   38,
       39,   79,   70,   71,   36,   34,   76,   35,   77,   37,
       80,   80,   78,   83,   61,   63,   62,   84,   72,   73,
       40,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   74,   84,   75,   65,    0,
       82,    0,    0,   48,   55,   49,   43,   85,    0,    0,
       82,    0,   46,   58,   44,   59,   45,    0,   81,    0,
        1,   47,    0,    0,   80,    0,    0,    0,   80,   68,
       57,   41,   66,   60,   67,   42,   84,   51,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,

       14,   16,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   50,   56,    0,    0,   54,
       85,    0,    0,   69,    0,    0,    0,    1,    0,   80,
       80,   80,    0,   81,   81,   52,   53,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   12,   84,   84,
       84,   84,   19,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   27,    0,    0,    0,   81,    0,    2,    0,
       81,   80,    0,   81,    0,   84,   28,   84,    4,    5,
       84,   84,   84,   84,   10,   84,   84,   13,   15,   84,
       84,   84,   84,   84,   84,   29,   84,   84,   84,   84,

       26,    0,    0,   81,   81,    0,   81,   84,    3,    6,
       84,   84,    9,   84,   84,   84,   84,   84,   31,   21,
       84,   84,   84,   84,   84,    0,    0,   81,   33,   84,
       84,   84,   84,   17,   84,   84,   84,   22,   23,   30,
       24,   25,    0,    0,   84,    8,   84,   84,   84,   20,
       32,    0,    0,    7,   84,   84,   84,    0,    0,   84,
       84,   18,    0,    0,   84,   84,    0,    0,   84,   11,
        0,    0,   84,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    7,    7,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,    7,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   44,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    3,    4,    5,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    6,    6,
        6,    3,    3,    3,    3,    3,    6,    6,    6,    6,
        3,    3,    3,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    3,    6,
        3,    3
    } ;

static yyconst flex_int16_t yy_base[282] =
    {   0,
        0,    0,  521,  522,  522,  522,  495,   57,  522,  494,
       55,   61,  522,  522,  493,   54,  522,   53,   53,   64,
       95,   78,  492,  522,   67,  491,   50,    0,  522,  522,
      490,  464,   36,   69,  474,   56,   70,  463,   46,  476,
       75,   68,   74,  452,  474,  522,   84,  522,  522,  122,
      522,  130,  123,  522,  522,  522,  483,  132,  497,  138,
      140,  141,  522,  522,  522,  522,  522,  489,  153,  492,
        0,  522,  208,  170,  180,  232,  164,  196,  244,  522,
      522,  479,  522,  522,  522,  478,    0,  522,  452,  452,
      461,  447,  463,  449,  456,  443,  457,  447,  441,  443,

      437,    0,  439,  435,  437,  449,  442,  436,  430,  434,
      435,  429,  436,  428,  426,  522,    0,  466,  157,  522,
      522,  465,  202,  522,  256,  461,  193,    0,  137,  135,
        0,  145,  260,  267,  184,  522,  522,  430,  412,  418,
      411,  401,   68,  186,  409,  411,  399,    0,  406,  393,
      392,  401,    0,  393,  389,  395,  381,  395,  394,  177,
      379,  392,    0,  272,  279,  213,  238,  155,  522,  412,
      277,    0,  280,  289,  309,  381,    0,  383,    0,    0,
      374,  383,  371,  373,    0,  373,  369,    0,    0,  369,
      368,  382,  361,  361,  342,    0,  355,  335,  344,  342,

        0,  307,  314,  312,  315,  318,  321,  335,    0,    0,
      311,  301,    0,  306,  302,  273,  282,  271,  259,    0,
      255,  249,  253,  240,  249,  315,  338,  330,    0,  236,
      232,  231,  216,    0,  220,  215,  194,    0,    0,    0,
        0,    0,  346,  350,  198,    0,  189,  169,  150,    0,
        0,  352,  356,    0,  145,  106,  115,  357,  360,  111,
      106,    0,  362,  366,  104,   89,  368,  377,   39,    0,
      400,  370,   71,  405,  408,  522,  449,  453,  455,  461,
      467
    } ;

static yyconst flex_int16_t yy_def[282] =
    {   0,
      276,    1,  276,  276,  276,  276,  276,  277,  276,  276,
      276,  278,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  279,  276,  276,
      276,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  276,  279,  276,  276,  277,
      276,  277,  277,  276,  276,  276,  276,  278,  276,  278,
      278,  278,  276,  276,  276,  276,  276,  276,  276,  280,
      281,  276,  276,  276,  276,  276,  276,   73,  276,  276,
      276,  276,  276,  276,  276,  276,  279,  276,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  276,  279,  276,  277,  276,
      276,  276,  278,  276,  276,  280,  276,  281,  276,   73,
       78,   78,  276,  276,  276,  276,  276,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  277,  278,  276,  276,  276,  276,  276,
      276,  132,  276,  276,  276,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  277,  278,  276,  276,  276,  276,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  277,  278,  276,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  277,  278,  279,  279,  279,  279,  279,  279,
      279,  277,  278,  279,  279,  279,  279,  277,  278,  279,
      279,  279,  277,  278,  279,  279,  277,  278,  279,  279,
      277,  278,  279,  277,  278,    0,  276,  276,  276,  276,
      276
    } ;

static yyconst flex_int16_t yy_nxt[585] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       29,   30,   31,    9,   32,   33,   34,   35,   36,   37,
       38,   28,   39,   28,   28,   28,   40,   28,   28,   41,
       42,   43,   44,   28,   45,   28,   28,   28,   46,   47,
       48,    9,   51,   55,   58,   59,   52,   64,   66,   68,
       61,   69,   69,   69,   85,   86,   70,   67,   65,   56,
      121,   71,   81,   77,   90,  102,   91,   57,   72,  273,
       82,   83,  103,  104,   74,   53,   79,   79,   79,   62,

       73,   96,  108,   92,   98,   77,  109,   97,  116,  106,
       93,   74,  111,   75,   75,   76,   77,   94,   99,  181,
      182,  110,   77,  100,   78,  107,  112,   51,   51,  113,
      270,   52,   52,   77,  118,   51,  276,   77,  269,   52,
      276,   61,  276,  117,  122,  276,  266,   61,  276,   61,
       61,   78,  265,  262,   73,  171,  171,  171,  125,  261,
       53,   53,   51,  172,  172,  172,   52,  168,   53,  129,
       62,   69,   69,   69,  119,  133,   62,  129,   62,   62,
      125,  260,  135,  135,  135,   77,  257,  170,  134,  134,
      134,  125,  123,  164,  131,   53,   74,  133,   75,   75,

       76,  276,  135,  135,  135,  168,  276,   77,  133,  276,
      169,   61,  125,  129,  131,  131,  131,  256,   77,  198,
      183,  129,  255,  129,  184,  170,  130,  130,  130,  133,
      199,  204,  204,  204,  131,  131,  254,   77,  165,   77,
       62,  251,  131,  131,  131,  131,  131,  131,   74,   77,
       76,   76,   76,  250,  249,  131,  167,  167,  167,   77,
       74,  166,   79,   79,   79,  173,  248,  132,  247,  166,
       77,   77,  175,  173,  167,  167,  167,   51,  174,  174,
      174,   52,   77,  276,  246,  134,  134,  134,   61,  245,
      242,   77,  241,  240,  175,  171,  171,  171,  205,  205,

      205,  239,  238,   77,  237,  175,  202,  174,  174,  174,
       53,  236,   51,  203,  206,  166,   52,   62,  276,  173,
       51,  235,  206,   61,   52,  234,  175,  207,  207,  207,
      204,  204,  204,  205,  205,  205,  228,  228,  228,  207,
      207,  207,  276,  233,  232,   53,  231,   61,  228,  228,
      228,   51,   62,  243,  276,   52,  226,   51,  230,   61,
      276,   52,   51,  227,  276,   61,   52,   51,  206,   61,
      276,   52,  229,   51,  276,   61,  244,   52,  225,   61,
      224,  276,  223,  252,   53,  258,   61,  253,   62,  259,
       53,  222,  221,  263,   62,   53,  264,  119,   62,  220,

       53,  123,  271,  267,   62,   51,   53,  268,   62,   52,
       51,  272,  276,  219,   52,   62,  218,   61,  217,  216,
      275,  215,  214,  213,  212,  211,  210,  209,  208,  126,
      201,  200,  197,  196,  195,  194,  193,  192,   53,  191,
      190,  189,  188,   53,  187,  186,   62,  185,  180,  179,
      274,   50,  178,   50,   50,   60,   60,  177,   60,   87,
       87,  126,  126,  126,  126,  126,  126,  128,  176,  128,
      128,  128,  128,  127,   60,   50,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,

      139,  138,  137,  136,  127,  124,  121,  120,  115,  114,
      105,  101,   95,   89,   88,   84,   80,   63,   54,   49,
      276,    3,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276
    } ;

static yyconst flex_int16_t yy_chk[585] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,   11,   12,   12,    8,   16,   18,   19,
       12,   19,   19,   19,   27,   27,   20,   18,   16,   11,
      273,   20,   25,   22,   33,   39,   33,   11,   20,  269,
       25,   25,   39,   39,   22,    8,   22,   22,   22,   12,

       21,   36,   42,   34,   37,   22,   42,   36,   47,   41,
       34,   21,   43,   21,   21,   21,   22,   34,   37,  143,
      143,   42,   21,   37,   21,   41,   43,   50,   53,   43,
      266,   50,   53,   21,   52,   52,   58,   22,  265,   52,
      130,   58,   60,   47,   61,   62,  261,   60,  130,   61,
       62,   21,  260,  257,   21,  129,  129,  129,   69,  256,
       50,   53,  119,  132,  132,  132,  119,  168,   52,   77,
       58,   69,   69,   69,   53,   74,   60,   77,   61,   62,
       69,  255,   77,   77,   77,   75,  249,  168,   74,   74,
       74,   69,   62,  119,  130,  119,   75,   74,   75,   75,

       75,   78,  135,  135,  135,  127,  123,   75,   74,   78,
      127,  123,   69,   73,   78,   78,   78,  248,   75,  160,
      144,   73,  247,   77,  144,  127,   73,   73,   73,   74,
      160,  166,  166,  166,   73,   73,  245,   76,  123,   75,
      123,  237,   73,   73,   73,   73,   73,   73,   76,   79,
       76,   76,   76,  236,  235,   78,  167,  167,  167,   76,
       79,  125,   79,   79,   79,  133,  233,   73,  232,  125,
       76,   79,  134,  133,  125,  125,  125,  164,  133,  133,
      133,  164,   79,  165,  231,  134,  134,  134,  165,  230,
      225,   76,  224,  223,  134,  171,  171,  171,  173,  173,

      173,  222,  221,   79,  219,  134,  164,  174,  174,  174,
      164,  218,  202,  165,  175,  125,  202,  165,  203,  133,
      226,  217,  175,  203,  226,  216,  134,  175,  175,  175,
      204,  204,  204,  205,  205,  205,  206,  206,  206,  207,
      207,  207,  227,  215,  214,  202,  212,  227,  228,  228,
      228,  243,  203,  226,  244,  243,  202,  252,  211,  244,
      253,  252,  258,  203,  259,  253,  258,  263,  175,  259,
      264,  263,  208,  267,  272,  264,  227,  267,  200,  272,
      199,  268,  198,  243,  243,  252,  268,  244,  244,  253,
      252,  197,  195,  258,  253,  258,  259,  243,  259,  194,

      263,  244,  267,  263,  264,  271,  267,  264,  272,  271,
      274,  268,  275,  193,  274,  268,  192,  275,  191,  190,
      272,  187,  186,  184,  183,  182,  181,  178,  176,  170,
      162,  161,  159,  158,  157,  156,  155,  154,  271,  152,
      151,  150,  149,  274,  147,  146,  275,  145,  142,  141,
      271,  277,  140,  277,  277,  278,  278,  139,  278,  279,
      279,  280,  280,  280,  280,  280,  280,  281,  138,  281,
      281,  281,  281,  126,  122,  118,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,

       90,   89,   86,   82,   70,   68,   59,   57,   45,   44,
       40,   38,   35,   32,   31,   26,   23,   15,   10,    7,
        3,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "go.l"
#line 2 "go.l"
#include <stdio.h>
#include <stdlib.h>
#include "y.tab.h"

int line_num = 1;
int char_num = 1;

char* tokens[3000];
size_t numToken = 0;
#line 690 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 116 "go.l"

#line 906 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 277 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 522 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "go.l"
{
				printf("Eating ...%s\n", yytext);
				char_num += strlen(yytext);
			}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 122 "go.l"
{
			printf("Eating ...%s\n", yytext);
			for(int i = 0; i < strlen(yytext); i++)
				if(yytext[i] == '\n')
					line_num++;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 128 "go.l"
{printf("%s\n", yytext); return break_;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "go.l"
{printf("%s\n", yytext); return case_;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "go.l"
{printf("%s\n", yytext); return chan_;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 131 "go.l"
{printf("%s\n", yytext); return const_;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 132 "go.l"
{printf("%s\n", yytext); return continue_;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 133 "go.l"
{printf("%s\n", yytext); return default_;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 134 "go.l"
{printf("%s\n", yytext); return defer_;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 135 "go.l"
{printf("%s\n", yytext); return else_;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "go.l"
{printf("%s\n", yytext); return fallthrough_;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 137 "go.l"
{printf("%s\n", yytext); return for_;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "go.l"
{printf("%s\n", yytext); return func_;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "go.l"
{printf("%s\n", yytext); return go_;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 140 "go.l"
{printf("%s\n", yytext); return goto_;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "go.l"
{printf("%s\n", yytext); return if_;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 142 "go.l"
{printf("%s\n", yytext); return import_;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 143 "go.l"
{printf("%s\n", yytext); return interface_;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 144 "go.l"
{printf("%s\n", yytext); return map_;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 145 "go.l"
{printf("%s\n", yytext); return package_;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "go.l"
{printf("%s\n", yytext); return range_;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 147 "go.l"
{printf("%s\n", yytext); return return_;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 148 "go.l"
{printf("%s\n", yytext); return select_;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 149 "go.l"
{printf("%s\n", yytext); return struct_;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 150 "go.l"
{printf("%s\n", yytext); return switch_;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 151 "go.l"
{printf("%s\n", yytext); return type_;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 152 "go.l"
{printf("%s\n", yytext); return var_;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 153 "go.l"
{printf("%s\n", yytext); return bool_;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 154 "go.l"
{printf("%s\n", yytext); return rune_;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 155 "go.l"
{printf("%s\n", yytext); return string_;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 156 "go.l"
{printf("%s\n", yytext); return print_;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 157 "go.l"
{printf("%s\n", yytext); return println_;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 158 "go.l"
{printf("%s\n", yytext); return append_;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 159 "go.l"
{printf("%s\n", yytext); return add_;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 160 "go.l"
{printf("%s\n", yytext); return minus_;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 161 "go.l"
{printf("%s\n", yytext); return mult_;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 162 "go.l"
{printf("%s\n", yytext); return div_;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 163 "go.l"
{printf("%s\n", yytext); return mod_;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 164 "go.l"
{printf("%s\n", yytext); return amp_;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 165 "go.l"
{printf("%s\n", yytext); return caret_;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 166 "go.l"
{printf("%s\n", yytext); return ls_;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 167 "go.l"
{printf("%s\n", yytext); return rs_;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 168 "go.l"
{printf("%s\n", yytext); return unknown_;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 169 "go.l"
{printf("%s\n", yytext); return add_eq_;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 170 "go.l"
{printf("%s\n", yytext); return minus_eq_;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 171 "go.l"
{printf("%s\n", yytext); return mult_eq_;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 172 "go.l"
{printf("%s\n", yytext); return div_eq_;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 173 "go.l"
{printf("%s\n", yytext); return mod_eq_;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 174 "go.l"
{printf("%s\n", yytext); return amp_eq_;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 175 "go.l"
{printf("%s\n", yytext); return vb_eq_;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 176 "go.l"
{printf("%s\n", yytext); return caret_eq_;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 177 "go.l"
{printf("%s\n", yytext); return ls_eq_;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 178 "go.l"
{printf("%s\n", yytext); return rs_eq_;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 179 "go.l"
{printf("%s\n", yytext); return unknown_eq_;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 180 "go.l"
{printf("%s\n", yytext); return and_;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 181 "go.l"
{printf("%s\n", yytext); return or_;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 182 "go.l"
{printf("%s\n", yytext); return arrow_;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 183 "go.l"
{printf("%s\n", yytext); return incre_;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 184 "go.l"
{printf("%s\n", yytext); return decre_;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 185 "go.l"
{printf("%s\n", yytext); return equality_;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 186 "go.l"
{printf("%s\n", yytext); return lt_;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 187 "go.l"
{printf("%s\n", yytext); return gt_;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 188 "go.l"
{printf("%s\n", yytext); return eq_;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 189 "go.l"
{printf("%s\n", yytext); return not_;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 190 "go.l"
{printf("%s\n", yytext); return not_eq_;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 191 "go.l"
{printf("%s\n", yytext); return lteq_;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 192 "go.l"
{printf("%s\n", yytext); return gteq_;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 193 "go.l"
{printf("%s\n", yytext); return decla_;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 194 "go.l"
{printf("%s\n", yytext); return etc_;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 195 "go.l"
{printf("%s\n", yytext); return lrbrac_;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 196 "go.l"
{printf("%s\n", yytext); return rrbrac_;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 197 "go.l"
{printf("%s\n", yytext); return lsbrac_;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 198 "go.l"
{printf("%s\n", yytext); return rsbrac_;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 199 "go.l"
{printf("%s\n", yytext); return lcbrac_;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 200 "go.l"
{printf("%s\n", yytext); return rcbrac_;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 201 "go.l"
{printf("%s\n", yytext); return comma_;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 202 "go.l"
{printf("%s\n", yytext); return dot_;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 203 "go.l"
{printf("%s\n", yytext); return colon_;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 204 "go.l"
{printf("%s\n", yytext); return vb_;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 206 "go.l"
{
					char ** temp;
					printf("%s\n", yytext);
					yylval.int_val = strtol(yytext, temp, 10);
					if(temp != NULL){
						printf("Integer parse error %s\n", yytext);
						return error_;
					}
					return int_lit_;
				}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 217 "go.l"
{
					char ** temp;
					printf("%s\n", yytext);
					yylval.float_val = strtof(yytext, temp);
					if(temp != NULL){
						printf("Integer parse error %s\n", yytext);
						return error_;
					}
					return float_lit_;
				}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 228 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return string_lit_;
				}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 240 "go.l"
{printf("%s\n", yytext); return semi_colon_;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 242 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return id_;
				}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 254 "go.l"
{
					char * val = (char *)malloc(strlen(yytext) + 1);
					if(val == NULL){
						printf("Mem Alloc Failed\n");
						exit(1);
					}
					printf("%s\n", yytext);
					strcpy(val, yytext);
					yylval.str_val = val;
					return rune_lit_;
				}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 266 "go.l"
char_num++;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 267 "go.l"

	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 268 "go.l"
{line_num++;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 269 "go.l"
ECHO;
	YY_BREAK
#line 1466 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 277 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 277 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 276);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 268 "go.l"



